-- MySQL Script generated by MySQL Workbench
-- Sat May 11 15:25:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotelbd` DEFAULT CHARACTER SET utf8 ;
USE `hotelbd` ;

-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador` (
  `idadministrador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadministrador`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `pais` (
  `idpais` INT NOT NULL AUTO_INCREMENT ,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpais`))
ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `ciudad` (
  `idciudad` INT NOT NULL AUTO_INCREMENT ,
  `idpais` INT,
  `nombre` VARCHAR(45) NOT NULL,
      FOREIGN KEY (`idpais`)
    REFERENCES `pais` (`idpais`),
  PRIMARY KEY (`idciudad`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `fecha_registro` DATE NOT NULL, 
  `fecha_actualizacion` DATE DEFAULT NULL,
  `estado` INT,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `proveedor` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `estado` INT,
  PRIMARY KEY (`idproveedor`))
ENGINE = InnoDB;






-- -----------------------------------------------------
-- Table `mydb`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel` (
  `idhotel` INT NOT NULL AUTO_INCREMENT ,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `habitaciones_disponibles` INT NOT NULL,
  `idciudad` INT,
  `idproveedor` INT,
    FOREIGN KEY (`idciudad`)
    REFERENCES `ciudad` (`idciudad`),
     FOREIGN KEY (`idproveedor`)
    REFERENCES `proveedor` (`idproveedor`),
  PRIMARY KEY (`idhotel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva` (
  `idreserva` INT NOT NULL,
  `fecha_entrada` DATE NOT NULL,
  `fecha_salida` DATE NOT NULL,
  `cantidad_personas` VARCHAR(45) NOT NULL,
  `hotel_idhotel` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_reserva_hotel1_idx` (`hotel_idhotel` ASC),
  INDEX `fk_reserva_usuario1_idx` (`usuario_idusuario` ASC) ,
  CONSTRAINT `fk_reserva_hotel1`
    FOREIGN KEY (`hotel_idhotel`)
    REFERENCES `hotel` (`idhotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habitacion` (
  `idhabitacion` INT NOT NULL AUTO_INCREMENT,
  `hotel_idhotel` INT NOT NULL,
  `capacidad` INT NOT NULL,
  `precio` INT NOT NULL,
  PRIMARY KEY (`idhabitacion`,`hotel_idhotel`),
  INDEX `fk_habitacion_hotel_idx` (`hotel_idhotel` ASC) ,
  CONSTRAINT `fk_habitacion_hotel`
    FOREIGN KEY (`hotel_idhotel`)
    REFERENCES `hotel` (`idhotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
